source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AMKeyboardAvoidingLayoutConstraint_Example', :exclusive => true do
  pod "AMKeyboardAvoidingLayoutConstraint", :path => "../"
end

target 'AMKeyboardAvoidingLayoutConstraint_Tests', :exclusive => true do
  pod "AMKeyboardAvoidingLayoutConstraint", :path => "../"
  
  pod 'Nimble', '~> 3.0'
end
