platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod "AMKeyboardAvoidingLayoutConstraint", :path => "../"

target 'AMKeyboardAvoidingLayoutConstraint_Example' do  
end
