source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

abstract_target 'default_pods' do
    pod "AMKeyboardAvoidingLayoutConstraint", :path => "../"

    target 'AMKeyboardAvoidingLayoutConstraint_Example' do
    end

    target 'AMKeyboardAvoidingLayoutConstraint_Tests' do
        pod 'Nimble', :git => 'https://github.com/Quick/Nimble', :branch => 'swift-3.0'
    end
end
